import Image from 'next/image';
import Link from 'next/link';
import type { Locale } from '@/shared/i18n/locales';
import type { Article, PageCopy } from '@/domain/content/content-repository';
import { SupportForm } from '@/presentation/components/support-form';

export function AboutPage({ locale }: { locale: Locale }) {
  const ar = locale === 'ar';
  return <main className="page-shell" id="main"><PageIntro eyebrow={ar ? 'من نحن' : 'About'} title={ar ? 'من المساحة إلى مطبخ واضح' : 'From space to a clear kitchen'} text={ar ? 'صفحة تعريفية تجريبية تحافظ على إيقاع المرجع وتستخدم محتوى قابلًا للاستبدال.' : 'A demo introduction that keeps the reference rhythm with replaceable content.'} /><div className="about-strip">{['/assets/cabinet-placeholder.svg', '/assets/cabinet-detail.svg', '/assets/cabinet-placeholder.svg'].map((src, index) => <div key={`${src}-${index}`}><Image src={src} alt={ar ? 'صورة مؤقتة لمطبخ ألوميتال' : 'Placeholder aluminum kitchen'} fill sizes="33vw" /></div>)}</div><div className="copy-panel"><span className="eyebrow">{ar ? 'رؤيتنا التجريبية' : 'Our demo direction'}</span><h2>{ar ? 'تشكيلات يمكن فهمها وتعديلها.' : 'Collections that are easy to understand and adapt.'}</h2><p>{ar ? 'نستخدم هذه النسخة لعرض علاقة الوحدات العلوية والسفلية والتصاميم المخصصة، دون ادعاء تاريخ أو ضمانات غير معتمدة.' : 'This version shows the relationship between upper units, base units, and custom designs without inventing history or unsupported guarantees.'}</p></div><div className="timeline">{(ar ? [['01', 'قياس المساحة'], ['02', 'اختيار التكوين'], ['03', 'مراجعة التصميم']] : [['01', 'Understand the space'], ['02', 'Choose a configuration'], ['03', 'Review a design']]).map(([number, title]) => <article key={number}><span>{number}</span><h3>{title}</h3><p className="demo-note">{ar ? 'خطوة نموذجية قابلة للاستبدال.' : 'A replaceable sample step.'}</p></article>)}</div><Faq locale={locale} /></main>;
}

export function SupportPage({ locale }: { locale: Locale }) { const ar = locale === 'ar'; return <main className="page-shell" id="main"><PageIntro eyebrow={ar ? 'الدعم' : 'Support'} title={ar ? 'كيف يمكننا مساعدتك؟' : 'How can we help?'} text={ar ? 'بيانات التواصل النهائية غير متوفرة بعد. استخدم النموذج التجريبي فقط.' : 'Final contact details are not supplied yet. Use this demo form only.'} /><section className="support-panel"><div><span className="eyebrow">{ar ? 'بيانات تجريبية' : 'Demo contact roles'}</span><h2>{ar ? 'استفسار عن منتج أو تصميم' : 'A product or design question'}</h2><p className="demo-note">{ar ? 'الهاتف والبريد والموقع سيتم استبدالها عند اعتماد بيانات المتجر.' : 'Phone, email, and location roles will be replaced when store details are approved.'}</p><p>hello@example.demo</p><p>+20 000 000 0000</p></div><div className="support-form"><SupportForm locale={locale} /></div></section></main>; }

export function BlogPage({ locale, content }: { locale: Locale; content: PageCopy }) { const ar = locale === 'ar'; return <main className="page-shell" id="main"><PageIntro eyebrow={ar ? 'المدونة' : 'Journal'} title={ar ? 'أفكار لتخطيط المطبخ' : 'Notes for planning a kitchen'} text={ar ? 'مقالات تجريبية عن الوحدات والمقاسات والتشطيبات.' : 'Demo articles about units, dimensions, and finishes.'} /><div className="blog-grid">{content.articles.map((article) => <ArticleCard key={article.slug} article={article} locale={locale} />)}</div></main>; }

export function ArticlePage({ locale, article }: { locale: Locale; article: Article }) { const ar = locale === 'ar'; return <main className="page-shell" id="main"><article className="article-page"><span className="eyebrow">{ar ? 'مقال تجريبي' : 'Demo article'}</span><h1>{article.title[locale]}</h1><p className="demo-note">{article.excerpt[locale]}</p><div className="article-image"><Image src={article.image} alt={ar ? 'صورة مؤقتة لمقال عن المطبخ' : 'Placeholder kitchen article image'} fill sizes="(max-width: 760px) 100vw, 760px" /></div><div className="article-body"><p>{article.body[locale]}</p></div><Link className="text-link" href={`/${locale}/blog`}>{ar ? 'العودة للمدونة' : 'Back to journal'} →</Link></article></main>; }

export function PolicyPage({ locale, title }: { locale: Locale; title: string }) { const ar = locale === 'ar'; return <main className="page-shell" id="main"><article className="policy-panel"><span className="eyebrow">{ar ? 'مسودة تجريبية' : 'Demo draft'}</span><h1>{title}</h1><p>{ar ? 'هذه صفحة سياسة مؤقتة للعرض فقط. لا تمثل شروطًا نهائية ولا تنشئ التزامات تشغيلية. سيتم استبدال النص بعد اعتماد بيانات المتجر والخدمات الفعلية.' : 'This is a temporary policy page for demonstration only. It does not represent final terms or create operational commitments. The text will be replaced after store details and actual services are approved.'}</p><p>{ar ? 'لا يتم إرسال أو حفظ بيانات النماذج في الإصدار الأول.' : 'Form data is not sent or saved in this first version.'}</p></article></main>; }

function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>; }
function ArticleCard({ article, locale }: { article: Article; locale: Locale }) { return <article className="blog-card"><Link href={`/${locale}/blog/${article.slug}`}><div className="blog-card-image"><Image src={article.image} alt={article.title[locale]} fill sizes="(max-width: 900px) 100vw, 33vw" /></div><h2>{article.title[locale]}</h2><p>{article.excerpt[locale]}</p></Link></article>; }
function Faq({ locale }: { locale: Locale }) { const ar = locale === 'ar'; return <section className="faq-list"><h2>{ar ? 'الأسئلة الشائعة' : 'Frequently asked questions'}</h2>{(ar ? ['هل هذه أسعار فعلية؟', 'هل يتم إرسال البيانات؟'] : ['Are these final prices?', 'Is any data sent?']).map((question) => <details key={question}><summary>{question}</summary><p>{ar ? 'لا، هذه نسخة تجريبية ولا يتم إرسال أو حفظ أي شيء.' : 'No. This is a demo and nothing is sent or saved.'}</p></details>)}</section>; }
