import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { mockCatalogRepository } from '@/data/catalog/mock-catalog-repository';
import { ProductActions } from '@/presentation/components/product-actions';
import { ProductGallery } from '@/presentation/components/product-gallery';
import { ProductCard } from '@/presentation/components/product-card';
import { formatEgp } from '@/shared/formatters/currency';
import { pageMetadata } from '@/shared/config/metadata';
import { isLocale } from '@/shared/i18n/locale-utils';

export async function generateStaticParams() { return ['ar', 'en'].flatMap((locale) => mockCatalogRepository.listProducts().map((product) => ({ locale, slug: product.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale: value, slug } = await params; if (!isLocale(value)) return {}; const product = mockCatalogRepository.getProductBySlug(slug); return product ? pageMetadata(value, product.title[value], product.description[value], `/shop/${slug}`) : {}; }
export default async function ProductPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale: value, slug } = await params; if (!isLocale(value)) notFound(); const product = mockCatalogRepository.getProductBySlug(slug); if (!product) notFound(); const locale = value; const ar = locale === 'ar'; const related = mockCatalogRepository.listProducts().filter((item) => item.id !== product.id).slice(0, 3); const price = product.price ?? product.startingPrice; return <main className="page-shell" id="main"><div className="breadcrumb"><Link href={`/${locale}/shop`}>{ar ? 'المتجر' : 'Shop'}</Link><span>/</span><span>{product.title[locale]}</span></div><div className="product-detail"><div className="product-detail-info"><span className="eyebrow">{product.category[locale]}</span><h1>{product.title[locale]}</h1><p className="product-description">{product.description[locale]}</p><p className="product-price">{price ? formatEgp(price, locale) : (ar ? 'السعر حسب التصميم' : 'Price by design')} <small>{product.price ? (ar ? 'سعر تجريبي' : 'demo price') : (ar ? 'يبدأ من' : 'starting from')}</small></p><dl className="spec-list"><div><dt>{ar ? 'المقاس' : 'Dimensions'}</dt><dd>{product.dimensions[locale]}</dd></div><div><dt>{ar ? 'التشطيب' : 'Finish'}</dt><dd>{product.finish[locale]}</dd></div><div><dt>{ar ? 'يشمل' : 'Includes'}</dt><dd>{product.includedUnits.map((unit) => unit[locale]).join(ar ? '، ' : ', ')}</dd></div></dl><ProductActions product={product} locale={locale} /></div><ProductGallery product={product} locale={locale} /></div><section className="related-products"><div className="section-heading"><h2>{ar ? 'قد يعجبك أيضًا' : 'You may also like'}</h2></div><div className="product-grid related-grid">{related.map((item) => <ProductCard key={item.id} product={item} locale={locale} />)}</div></section></main>; }
